INSERT INTO `libros` (`id`, `titulo`, `autor`, `editorial`, `fecha`, `tematica`) VALUES
(1, 'HARRY POTTER Y EL PRISIONERO DE AZKABAN', 'J.K ROWINS', 'SALAMANDRA', '2006-9-26', 'INFANTIL'),
(2, 'EL GRAN LABERINTO', 'FERNANDO SABATER PEREZ', 'ARIEL', '2006-9-26', 'FICCION'),
(3, 'ROMEO Y JULIETA', 'WILLIAM SHAKESPEARE', 'SALAMANDRA', '2006-9-26', 'ROMANTICA'),    	
(4, 'LA CARTA ESFERICA', 'ARTURO PEREZ LOPEZ', 'SALAMANDRA', '2006-9-29', 'FICCION'),
(5, 'CODIGO DA VINCI', 'DAN BROWN', 'ARIEL', '2006-9-29', 'FICCION'),
(6, 'MUCHO RUIDO Y POCAS NUECES', 'WILLIAM SHAKESPEARE', 'SALAMANDRA', '2006-9-29', 'ROMANTICA'),
(7, 'PROTOCOLO', 'JOSE LOPEZ MURILLO', 'SALAMANDRA', '2006-9-6', 'SOCIAL'),
(8, 'LINUX', 'FERNANDO SABATER PEREZ', 'ARIEL', '2006-9-6', 'INFORMATICA'),
(9, 'EL TUMULTO', 'H.P LOVERCRAFT', 'DEBATE', '2006-9-6', 'CIENCIA'),
(10, 'PERSONAJES MITICOS', 'RICHARD HOLLIGHAM', 'DEBATE', '2006-9-7', 'ENTRETENIMIENTO'),
(11, 'EL TIEMPO', 'J.K ROWINS', 'SALAMANDRA', '2006-9-7', 'CIENCIA'),
(12, 'DIETAS MEDITERRANEAS', 'ARTURO PEREZ LOPEZ', 'ARIEL', '2006-9-16', 'ASTRONOMIA'),
(13, 'ANGELES Y DEMONIOS', 'DAN BROWN', 'ARIEL', '2006-9-17', 'FICCION'),
(14, 'FORTALEZA DIGITAL', 'DAN BROWN', 'ARIEL', '2006-10-6', 'FICCION'),
(15, 'CAPITAN ALATRISTE', 'ARTURO PEREZ LOPEZ', 'ALFAGUARA', '2006-10-9', 'FICCION'),
(16, 'PIEL DE TAMBOR', 'ARTURO PEREZ LOPEZ', 'ALFAGUARA', '2006-10-16', 'FICCION'),
(17, 'TIEMPOS DE COLERA', 'GABRIEL GARCIA GARCIA', 'OVEJA NEGRA', '2006-9-1', 'OCIO'),
(18, 'NOTICIA DE UN SECUESTRO','GABRIEL GARCIA GARCIA', 'ALFAGUARA','2006-12-7', 'FICCION');

INSERT INTO `usuarios` (`id`, `usuario`, `password`) VALUES

(1, 'admin', '456'), (2, 'itic', 'itic');